# Generated by Django 5.2.4 on 2025-07-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carditem',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
