# Generated by Django 5.2.4 on 2025-07-30 19:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_amount_alter_product_rating'),
        ('order', '0002_alter_carditem_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardItem',
            new_name='CartItem',
        ),
    ]
